### ISSUE TITLE
Improve the color of the icons

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/segallio#60]
```css
.svg-inline--fa .fa-primary {
    fill: #ffd7a0;
    opacity: 1;
    opacity: var(--fa-primary-opacity, 1);
}

.svg-inline--fa .fa-secondary {
    fill: #17546a;
    opacity: 0.4;
    opacity: var(--fa-secondary-opacity, 0.4);
}
```

![image](https://user-images.githubusercontent.com/1222368/90507124-0da03500-e15e-11ea-9b43-3ee3b8a5e5f1.png)
